name: Set up PostgreSQL
description: Start PostgreSQL (runner service or Docker), create user, databases, and import schemas

inputs:
  use-docker:
    description: Use Docker container instead of runner service
    required: false
    default: 'false'
  image:
    description: Docker image (only used with use-docker)
    required: false
    default: 'postgres'
  version:
    description: Docker image version (only used with use-docker)
    required: false
    default: '16'
  container-name:
    description: Container name (only used with use-docker)
    required: false
    default: 'pgsql-test'
  host:
    description: Database host
    required: false
    default: '127.0.0.1'
  port:
    description: Database port
    required: false
    default: '5432'
  username:
    description: Database username
    required: false
    default: 'postgres'
  password:
    description: Database password
    required: false
    default: 'postgres'
  db-name:
    description: Primary database name
    required: false
    default: 'laravel'
  db-names:
    description: JSON array of additional database names
    required: false
    default: '[]'
  wait:
    description: Wait for service to be ready before continuing
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Validate database names
      shell: bash
      run: |
        if ! echo '${{ inputs.db-names }}' | jq empty 2>/dev/null; then
          echo "::error::Invalid JSON in db-names input: ${{ inputs.db-names }}"
          exit 1
        fi

    - name: Start runner PostgreSQL service
      if: inputs.use-docker != 'true'
      shell: bash
      run: sudo systemctl start postgresql.service

    - name: Start Docker container
      if: inputs.use-docker == 'true'
      shell: bash
      run: |
        if ! docker ps -a --format '{{.Names}}' | grep -qx '${{ inputs.container-name }}'; then
          docker run -d \
            --name ${{ inputs.container-name }} \
            -e POSTGRES_USER=${{ inputs.username }} \
            -e POSTGRES_PASSWORD=${{ inputs.password }} \
            -p ${{ inputs.port }}:5432 \
            --health-cmd="pg_isready -U ${{ inputs.username }}" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            ${{ inputs.image }}:${{ inputs.version }}
        fi

    - name: Wait for PostgreSQL to be healthy
      if: inputs.wait == 'true'
      uses: ./.github/actions/setup-pgsql/healthcheck
      with:
        use-docker: ${{ inputs.use-docker }}
        container-name: ${{ inputs.container-name }}
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}

    - name: Create databases
      if: inputs.wait == 'true'
      uses: ./.github/actions/setup-pgsql/create-databases
      with:
        use-docker: ${{ inputs.use-docker }}
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        db-name: ${{ inputs.db-name }}
        db-names: ${{ inputs.db-names }}

    - name: Import schemas
      if: inputs.wait == 'true'
      uses: ./.github/actions/setup-pgsql/import-schemas
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        db-name: ${{ inputs.db-name }}
        db-names: ${{ inputs.db-names }}
