name: PostgreSQL Health Check
description: Wait for PostgreSQL to be healthy and ready

inputs:
  use-docker:
    description: Use Docker container instead of runner service
    required: false
    default: 'false'
  container-name:
    description: Container name (only used with use-docker)
    required: false
    default: 'pgsql-test'
  host:
    description: Database host
    required: false
    default: '127.0.0.1'

runs:
  using: composite
  steps:
    - name: Wait for PostgreSQL
      shell: bash
      run: |
        if [ "${{ inputs.use-docker }}" = "true" ]; then
          timeout 60 sh -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ inputs.container-name }} | grep -q healthy; do sleep 2; done'
          echo "✓ PostgreSQL is healthy"
        else
          timeout 30 sh -c 'until pg_isready -h ${{ inputs.host }} -p 5432 2>/dev/null; do sleep 1; done'
          echo "✓ PostgreSQL is ready"
        fi
