name: MySQL Create Databases
description: Create MySQL databases

inputs:
  host:
    description: Database host
    required: false
    default: '127.0.0.1'
  username:
    description: Database username
    required: false
    default: 'root'
  password:
    description: Database password
    required: false
    default: 'root'
  db-name:
    description: Primary database name
    required: false
    default: 'laravel'
  db-names:
    description: JSON array of additional database names
    required: false
    default: '[]'

runs:
  using: composite
  steps:
    - name: Create databases
      shell: bash
      run: |
        echo "Creating primary database: ${{ inputs.db-name }}"
        mysql --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} \
          -e "CREATE DATABASE IF NOT EXISTS \`${{ inputs.db-name }}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

        for db_name in $(echo '${{ inputs.db-names }}' | jq -r '.[]'); do
          echo "Creating additional database: $db_name"
          mysql --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} \
            -e "CREATE DATABASE IF NOT EXISTS \`$db_name\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        done
