name: Set up OpenSearch
description: Start OpenSearch container

inputs:
  version:
    description: Docker image version
    required: false
    default: '2.13.0'
  container-name:
    description: Container name
    required: false
    default: 'opensearch-test'
  port:
    description: Port
    required: false
    default: '9200'
  java-opts:
    description: JVM heap options
    required: false
    default: '-Xms512m -Xmx512m'
  wait:
    description: Wait for service to be ready before continuing
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Start container
      shell: bash
      run: |
        if ! docker ps -a --format '{{.Names}}' | grep -qx '${{ inputs.container-name }}'; then
          docker run -d \
            --name ${{ inputs.container-name }} \
            -e OPENSEARCH_INITIAL_ADMIN_PASSWORD='Test1234!' \
            -e node.name=es01 \
            -e cluster.name=es-docker-cluster \
            -e discovery.type=single-node \
            -e bootstrap.memory_lock=true \
            -e http.compression=true \
            -e http.port=9200 \
            -e plugins.security.disabled=true \
            -e "ES_JAVA_OPTS=${{ inputs.java-opts }}" \
            -p ${{ inputs.port }}:9200 \
            --health-cmd="curl -f http://localhost:9200/_cluster/health || exit 1" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            opensearchproject/opensearch:${{ inputs.version }}
        fi

    - name: Wait for healthy status
      if: inputs.wait == 'true'
      shell: bash
      run: |
        echo "Waiting for OpenSearch to be healthy..."
        timeout 60 sh -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ inputs.container-name }} | grep -q healthy; do sleep 2; done'

    - name: Verify host connectivity
      if: inputs.wait == 'true'
      shell: bash
      run: |
        echo "Verifying OpenSearch is accessible on port ${{ inputs.port }}..."
        curl -sf http://127.0.0.1:${{ inputs.port }}/_cluster/health || {
          echo "::warning::OpenSearch health check passed but host connectivity failed"
          docker logs ${{ inputs.container-name }} --tail 20
          exit 1
        }
