name: Redis Health Check
description: Wait for Redis to be healthy and ready

inputs:
  container-name:
    description: Container name
    required: false
    default: 'redis-test'

runs:
  using: composite
  steps:
    - name: Wait for Redis
      shell: bash
      run: |
        timeout 60 sh -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ inputs.container-name }} | grep -q healthy; do sleep 2; done'
        echo "✓ Redis is healthy"
