name: Set up Node and npm
description: Set up Node.js, cache dependencies, install, and build

inputs:
  build-script:
    description: npm script to run for build (e.g. "build", "prod")
    required: false
    default: ''
  node-version-file:
    description: Path to node version file
    required: false
    default: '.nvmrc'

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci --prefer-offline --no-audit
        else
          npm install --no-audit
        fi

    - name: Build
      shell: bash
      run: |
        if [ -n "${{ inputs.build-script }}" ]; then
          echo "Running: npm run ${{ inputs.build-script }}"
          npm run ${{ inputs.build-script }}
        elif [ -f vite.config.js ] || [ -f vite.config.ts ]; then
          npm run build
        elif [ -f webpack.mix.js ]; then
          npm run prod
        else
          echo "::error::Could not detect bundler (no vite.config.js, vite.config.ts, or webpack.mix.js). Set the build-script input explicitly."
          exit 1
        fi
