name: PostgreSQL Create Databases
description: Create PostgreSQL databases and user

inputs:
  use-docker:
    description: Use Docker container instead of runner service
    required: false
    default: 'false'
  host:
    description: Database host
    required: false
    default: '127.0.0.1'
  port:
    description: Database port
    required: false
    default: '5432'
  username:
    description: Database username
    required: false
    default: 'postgres'
  password:
    description: Database password
    required: false
    default: 'postgres'
  db-name:
    description: Primary database name
    required: false
    default: 'laravel'
  db-names:
    description: JSON array of additional database names
    required: false
    default: '[]'

runs:
  using: composite
  steps:
    - name: Create user (runner service)
      if: inputs.use-docker != 'true'
      shell: bash
      run: |
        sudo -u postgres psql -c "CREATE USER ${{ inputs.username }} WITH PASSWORD '${{ inputs.password }}';" 2>/dev/null || \
          sudo -u postgres psql -c "ALTER USER ${{ inputs.username }} WITH PASSWORD '${{ inputs.password }}';"

    - name: Create databases
      shell: bash
      env:
        PGHOST: ${{ inputs.host }}
        PGPORT: ${{ inputs.port }}
        PGUSER: ${{ inputs.username }}
        PGPASSWORD: ${{ inputs.password }}
      run: |
        echo "Creating primary database: ${{ inputs.db-name }}"
        createdb --owner=${{ inputs.username }} "${{ inputs.db-name }}" 2>/dev/null || echo "Database ${{ inputs.db-name }} already exists"

        for db_name in $(echo '${{ inputs.db-names }}' | jq -r '.[]'); do
          echo "Creating additional database: $db_name"
          createdb --owner=${{ inputs.username }} "$db_name" 2>/dev/null || echo "Database $db_name already exists"
        done
