name: Set up Redis
description: Start Redis container

inputs:
  image:
    description: Docker image
    required: false
    default: 'valkey/valkey'
  version:
    description: Docker image version
    required: false
    default: 'alpine'
  container-name:
    description: Container name
    required: false
    default: 'redis-test'
  port:
    description: Port
    required: false
    default: '6379'

runs:
  using: composite
  steps:
    - name: Start container
      shell: bash
      run: |
        docker run -d \
          --name ${{ inputs.container-name }} \
          -p ${{ inputs.port }}:6379 \
          --health-cmd="redis-cli ping" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=3 \
          ${{ inputs.image }}:${{ inputs.version }}

    - name: Wait for healthy status
      shell: bash
      run: |
        echo "Waiting for Redis to be healthy..."
        timeout 60 sh -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ inputs.container-name }} | grep -q healthy; do sleep 2; done'
