name: Set up MySQL
description: Start MySQL (runner service or Docker), create databases, and import schemas

inputs:
  use-docker:
    description: Use Docker container instead of runner service
    required: false
    default: 'false'
  image:
    description: Docker image (only used with use-docker)
    required: false
    default: 'mysql'
  version:
    description: Docker image version (only used with use-docker)
    required: false
    default: '8.0.32'
  container-name:
    description: Container name (only used with use-docker)
    required: false
    default: 'mysql-test'
  host:
    description: Database host
    required: false
    default: '127.0.0.1'
  port:
    description: Database port
    required: false
    default: '3306'
  username:
    description: Database username
    required: false
    default: 'root'
  password:
    description: Database password
    required: false
    default: 'root'
  db-name:
    description: Primary database name
    required: false
    default: 'laravel'
  db-names:
    description: JSON array of additional database names
    required: false
    default: '[]'
  wait:
    description: Wait for service to be ready before continuing
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Validate database names
      if: inputs.wait == 'true'
      shell: bash
      run: |
        if ! echo '${{ inputs.db-names }}' | jq empty 2>/dev/null; then
          echo "::error::Invalid JSON in db-names input: ${{ inputs.db-names }}"
          exit 1
        fi

    - name: Start runner MySQL service
      if: inputs.use-docker != 'true'
      shell: bash
      run: sudo systemctl start mysql.service

    - name: Start Docker container
      if: inputs.use-docker == 'true'
      shell: bash
      run: |
        if ! docker ps -a --format '{{.Names}}' | grep -qx '${{ inputs.container-name }}'; then
          docker run -d \
            --name ${{ inputs.container-name }} \
            -e MYSQL_ROOT_PASSWORD=${{ inputs.password }} \
            -p ${{ inputs.port }}:3306 \
            --health-cmd="mysqladmin ping --silent" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            ${{ inputs.image }}:${{ inputs.version }}
        fi

    - name: Wait for MySQL to be healthy
      if: inputs.wait == 'true'
      shell: bash
      run: |
        if [ "${{ inputs.use-docker }}" = "true" ]; then
          echo "Waiting for MySQL to be healthy..."
          timeout 60 sh -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ inputs.container-name }} | grep -q healthy; do sleep 2; done'
        else
          echo "Waiting for MySQL to accept connections..."
          timeout 30 sh -c 'until mysqladmin ping --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} --silent 2>/dev/null; do sleep 1; done'
        fi

    - name: Create databases
      if: inputs.wait == 'true'
      shell: bash
      run: |
        echo "Creating primary database: ${{ inputs.db-name }}"
        mysql --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} \
          -e "CREATE DATABASE IF NOT EXISTS \`${{ inputs.db-name }}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

        for db_name in $(echo '${{ inputs.db-names }}' | jq -r '.[]'); do
          echo "Creating additional database: $db_name"
          mysql --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} \
            -e "CREATE DATABASE IF NOT EXISTS \`$db_name\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        done

    - name: Import schemas
      if: inputs.wait == 'true'
      shell: bash
      run: |
        schema_candidates=(
          "database/schema/${{ inputs.db-name }}.sql"
          "database/schema/${{ inputs.db-name }}-schema.sql"
          "database/schema/mysql.sql"
          "database/schema/mysql-schema.sql"
        )
        for schema_file in "${schema_candidates[@]}"; do
          if [ -f "$schema_file" ]; then
            echo "Importing schema: $schema_file"
            mysql --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} "${{ inputs.db-name }}" < "$schema_file"
            break
          fi
        done

        for db_name in $(echo '${{ inputs.db-names }}' | jq -r '.[]'); do
          for schema_file in "database/schema/${db_name}.sql" "database/schema/${db_name}-schema.sql"; do
            if [ -f "$schema_file" ]; then
              echo "Importing schema: $schema_file"
              mysql --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} "$db_name" < "$schema_file"
              break
            fi
          done
        done
