name: Set up MySQL
description: Start MySQL (runner service or Docker), create databases, and import schemas

inputs:
  use-docker:
    description: Use Docker container instead of runner service
    required: false
    default: 'false'
  image:
    description: Docker image (only used with use-docker)
    required: false
    default: 'mysql'
  version:
    description: Docker image version (only used with use-docker)
    required: false
    default: '8.0.32'
  container-name:
    description: Container name (only used with use-docker)
    required: false
    default: 'mysql-test'
  host:
    description: Database host
    required: false
    default: '127.0.0.1'
  port:
    description: Database port
    required: false
    default: '3306'
  username:
    description: Database username
    required: false
    default: 'root'
  password:
    description: Database password
    required: false
    default: 'root'
  db-name:
    description: Primary database name
    required: false
    default: 'laravel'
  db-names:
    description: JSON array of additional database names
    required: false
    default: '[]'
  wait:
    description: Wait for service to be ready before continuing
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Validate database names
      shell: bash
      run: |
        if ! echo '${{ inputs.db-names }}' | jq empty 2>/dev/null; then
          echo "::error::Invalid JSON in db-names input: ${{ inputs.db-names }}"
          exit 1
        fi

    - name: Start runner MySQL service
      if: inputs.use-docker != 'true'
      shell: bash
      run: |
        sudo systemctl start mysql.service
        if [ "${{ inputs.wait }}" = "true" ]; then
          echo "Waiting for MySQL to accept connections..."
          timeout 30 sh -c 'until mysqladmin ping --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} --silent 2>/dev/null; do sleep 1; done'
        fi

    - name: Start Docker container
      if: inputs.use-docker == 'true'
      shell: bash
      run: |
        docker run -d \
          --name ${{ inputs.container-name }} \
          -e MYSQL_ROOT_PASSWORD=${{ inputs.password }} \
          -p ${{ inputs.port }}:3306 \
          --health-cmd="mysqladmin ping --silent" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=3 \
          ${{ inputs.image }}:${{ inputs.version }}

    - name: Wait for MySQL to be healthy
      if: inputs.wait == 'true'
      uses: ./.github/actions/setup-mysql/healthcheck
      with:
        use-docker: ${{ inputs.use-docker }}
        container-name: ${{ inputs.container-name }}
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Create databases
      if: inputs.wait == 'true'
      uses: ./.github/actions/setup-mysql/create-databases
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        db-name: ${{ inputs.db-name }}
        db-names: ${{ inputs.db-names }}

    - name: Import schemas
      if: inputs.wait == 'true'
      uses: ./.github/actions/setup-mysql/import-schemas
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        db-name: ${{ inputs.db-name }}
        db-names: ${{ inputs.db-names }}
