name: MySQL Health Check
description: Wait for MySQL to be healthy and ready

inputs:
  use-docker:
    description: Use Docker container instead of runner service
    required: false
    default: 'false'
  container-name:
    description: Container name (only used with use-docker)
    required: false
    default: 'mysql-test'
  host:
    description: Database host
    required: false
    default: '127.0.0.1'
  username:
    description: Database username
    required: false
    default: 'root'
  password:
    description: Database password
    required: false
    default: 'root'

runs:
  using: composite
  steps:
    - name: Wait for MySQL
      shell: bash
      run: |
        if [ "${{ inputs.use-docker }}" = "true" ]; then
          timeout 60 sh -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ inputs.container-name }} | grep -q healthy; do sleep 2; done'
          echo "✓ MySQL is healthy"
        else
          timeout 30 sh -c 'until mysqladmin ping --host=${{ inputs.host }} --user=${{ inputs.username }} --password=${{ inputs.password }} --silent 2>/dev/null; do sleep 1; done'
          echo "✓ MySQL is ready"
        fi
